# Data Transformation

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data2.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

### Sorting and Ranking

In [3]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [4]:
df.sort_values("Year" , ascending = False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [10]:
df.sort_values(["Year", "IMDb"]).copy

<bound method NDFrame.copy of                  Actor                      Film  Year            Genre  \
2           Aamir Khan                    Dangal  2016        Biography
1          Salman Khan           Tiger Zinda Hai  2017           Action
10        Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
4        Ranveer Singh                 Padmaavat  2018       Historical
6        Rajkummar Rao                     Stree  2018    Horror Comedy
5   Ayushmann Khurrana                 Andhadhun  2018         Thriller
7       Hrithik Roshan                       War  2019           Action
8         Akshay Kumar                Good Newwz  2019           Comedy
11       Vicky Kaushal  Uri: The Surgical Strike  2019           Action
3        Ranbir Kapoor                Brahmastra  2022          Fantasy
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
0       Shah Rukh Khan                   Pathaan  2023           Action

    BoxOffice(INR Crore)  IMDb
2                   2024   8.4
1                    565   6.0
10                   201   6.1
4                    585   7.0
6                    180   7.5
5                    111   8.3
7                    475   6.5
8                    318   7.0
11                   342   8.2
3                    431   5.6
9                    266   5.9
0                   1050   7.2  >

In [11]:
df.reset_index(drop=True, inplace=True)

In [12]:
df2

<bound method NDFrame.copy of                  Actor                      Film  Year            Genre  \
2           Aamir Khan                    Dangal  2016        Biography
1          Salman Khan           Tiger Zinda Hai  2017           Action
10        Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
4        Ranveer Singh                 Padmaavat  2018       Historical
6        Rajkummar Rao                     Stree  2018    Horror Comedy
5   Ayushmann Khurrana                 Andhadhun  2018         Thriller
7       Hrithik Roshan                       War  2019           Action
8         Akshay Kumar                Good Newwz  2019           Comedy
11       Vicky Kaushal  Uri: The Surgical Strike  2019           Action
3        Ranbir Kapoor                Brahmastra  2022          Fantasy
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
0       Shah Rukh Khan                   Pathaan  2023           Action

    BoxOffice(INR Crore)  IMDb
2                   2024   8.4
1                    565   6.0
10                   201   6.1
4                    585   7.0
6                    180   7.5
5                    111   8.3
7                    475   6.5
8                    318   7.0
11                   342   8.2
3                    431   5.6
9                    266   5.9
0                   1050   7.2  >

In [13]:
df.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [15]:
df["Rank"] = df["IMDb"].rank(ascending = False, method="dense")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0

In [16]:
df = df[["Film", "Actor", "Year", "Genre", "IMDb", "BoxOffice(INR Crore)"]] 
df

,Film,Actor,Year,Genre,IMDb,BoxOffice(INR Crore)
0,Pathaan,Shah Rukh Khan,2023,Action,7.2,1050
1,Tiger Zinda Hai,Salman Khan,2017,Action,6.0,565
2,Dangal,Aamir Khan,2016,Biography,8.4,2024
3,Brahmastra,Ranbir Kapoor,2022,Fantasy,5.6,431
4,Padmaavat,Ranveer Singh,2018,Historical,7.0,585
5,Andhadhun,Ayushmann Khurrana,2018,Thriller,8.3,111
6,Stree,Rajkummar Rao,2018,Horror Comedy,7.5,180
7,War,Hrithik Roshan,2019,Action,6.5,475
8,Good Newwz,Akshay Kumar,2019,Comedy,7.0,318
9,Bhool Bhulaiyaa 2,Kartik Aaryan,2022,Horror Comedy,5.9,266
10,Badrinath Ki Dulhania,Varun Dhawan,2017,Romantic Comedy,6.1,201
11,Uri: The Surgical Strike,Vicky Kaushal,2019,Action,8.2,342