## 🔹Sorting & Ranking

In [2]:
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Marks": [70, 50, 90, 60]
})

#### Q1: Sort the DataFrame by Marks in descending order.

In [4]:
df.sort_values("Marks" , ascending=False)

  Name  Marks
2    C     70
1    B     60
0    A     50

#### Q2: Create a new column "Rank" based on Marks.

In [13]:
df["Rank"] = df["Marks"].rank(ascending=False)
df

  Name  Marks  Rank
0    A     50   3.0
1    B     60   2.0
2    C     70   1.0

## Renaming Columns & Index

In [14]:
df = pd.DataFrame({
    "name": ["A", "B"],
    "marks": [50, 60]
})

#### Q1: Rename "name" → "Name" and "marks" → "Marks".

In [21]:
df.rename(columns={"name" : "Name" , "marks" : "Marks"} , inplace = True)
df

  Name  Marks
0    A     50
1    B     60

#### Q2: Change index to ["a", "b"]

In [26]:
df.rename(index={0:"a", 1: "b"}, inplace=True)
df

  Name  Marks
a    A     50
b    B     60

## Changing Column Order

In [27]:
df = pd.DataFrame({
    "A": [1, 2],
    "B": [3, 4],
    "C": [5, 6]
})

#### Q1: Rearrange columns to order: A,B,C.