In [1]:
import pandas as pd

In [2]:
data = [["Yash" , 90] , ["Shivel", 30] , ["Ashish" , 60]]
data

[['Yash', 90], ['Shivel', 30], ['Ashish', 60]]

In [3]:
pd.DataFrame(data, columns = ["Name" , "Marks"])

     Name  Marks
0    Yash     90
1  Shivel     30
2  Ashish     60

In [4]:
data = {"a" :[1,2,3] , "b":[4,5,6]}
data

{'a': [1, 2, 3], 'b': [4, 5, 6]}

In [5]:
pd.DataFrame(data)

   a  b
0  1  4
1  2  5
2  3  6

### Data Frame in Numpy

In [6]:
import numpy as np

In [7]:
arr = np.array([[1,2] , [4,5]])
df = pd.DataFrame(arr, columns = ["A" , "B"])
df

   A  B
0  1  2
1  4  5

#### Excel file read

In [8]:
df = pd.read_excel("data.xlsx")
df

     Name Colleges  CGPA
0    Yash     Dbuu   8.7
1  Ashish      Uit   9.8
2  Shivel      Geu   7.8
3   Suraj     Upes   6.8
4   Sagar      Dit   5.8
5  Akshay       IU   6.9

#### Read csv file

In [9]:
df = pd.read_csv("data.csv")
df

     Name Colleges  CGPA
0    Yash     Dbuu   8.7
1  Ashish      Uit   9.8
2  Shivel      Geu   7.8
3   Suraj     Upes   6.8
4   Sagar      Dit   5.8
5  Akshay       IU   6.9

#### Read json file

In [12]:
df = pd.read_json("data.json")
df

    name language
0   Yash   Python
1  Sagar       JS

#### Read URL

In [17]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## Exploratory Data Analysis(EDA)

##### Exploratory Data Analysis (EDA) is an essential first step in any data science project.

It involves taking a deep look at the dataset to understand its structure, spot patterns, identify anomalies, and uncover relationships between variables. This process includes generating summary statistics, checking for missing or duplicate data, and creating visualizations like histograms, box plots, and scatter plots. The goal of EDA is to get a clear picture of what the data is telling you before applying any analysis or machine learning models.

By exploring the data thoroughly, you can make better decisions about how to clean, transform, and model it effectively.

Once your DataFrame is ready, run these to understand your data:

In [19]:
df.head()         # First 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
df.tail() #Last five rows

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [23]:
df.info()         # Column info: types, non-nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [25]:
df.describe()     # Stats for numeric columns

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [27]:
df.columns        # List of column names

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [28]:
df.shape          # (rows, columns)

(244, 7)