## 🔹 1. Missing Values

#### Q1: Find missing values in each column and fill missing values in "Age" with the mean.

In [1]:
import pandas as pd

data = {
    "Name": ["Amit", "Baby", "Cat", "Dog"],
    "Age": [20, None, 22, None],
    "City": ["Delhi", "Mumbai", None, "Chennai"]
}
df = pd.DataFrame(data)
df

   Name   Age     City
0  Amit  20.0    Delhi
1  Baby   NaN   Mumbai
2   Cat  22.0     None
3   Dog   NaN  Chennai

In [2]:
df.isnull().sum()

Name    0
Age     2
City    1
dtype: int64

In [3]:
df["Age"].fillna(df["Age"].mean())

0    20.0
1    21.0
2    22.0
3    21.0
Name: Age, dtype: float64

#### Q2: Drop all rows where any value is missing.

In [4]:
df.dropna()

   Name   Age   City
0  Amit  20.0  Delhi

## 🔹 2. String Cleaning

#### Q1: Convert all names to lowercase.

In [5]:
df["Name"].str.lower()

0    amit
1    baby
2     cat
3     dog
Name: Name, dtype: object

#### Q2: Capitalize the first letter of each name.

In [10]:
df["Name"].str.capitalize()

0    Amit
1    Baby
2     Cat
3     Dog
Name: Name, dtype: object

## 🔹 3. Type Conversion

In [24]:
import pandas as pd
df = pd.DataFrame({
    "Price": ["100", "200", "300"],
    "Age": ["20", "twenty", "25"]
})

#### Q1: Convert "Price" to integer.

In [21]:
df["Price"].astype(int)

0    100
1    200
2    300
Name: Price, dtype: int64

#### Q2: Convert "Age" to numeric, invalid values → NaN.

In [32]:
df["Age"]= pd.to_numeric(df["Age"], errors="coerce")
df

  Price   Age
0   100  20.0
1   200   NaN
2   300  25.0

## 🔹 4. apply()

#### Q1: Create "Result": Fail/Pass.

In [42]:
df = pd.DataFrame({
    "Marks": [40, 55, 70, 90]
})

In [46]:
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x > 50 else "Fail")
df

   Marks Result
0     40   Fail
1     55   Pass
2     70   Pass
3     90   Pass

#### Q2: Create "Square" column.

In [47]:
df["Result"] = df["Marks"].apply(lambda x: x*x)
df

   Marks  Result
0     40    1600
1     55    3025
2     70    4900
3     90    8100

## 🔹 5. map()

In [52]:
df = pd.DataFrame({
    "Grade": ["A", "B", "C", "A"],
    "Status": ["Yes", "No", "Yes", "No"]
})

#### Q1: Map grades to words.

In [54]:
grade_map = {"A" : "Excellent" , "B" : "Good" , "C" : "Average"}
df["Grade"] = df["Grade"].map(grade_map)
df

  Grade Status
0   NaN    Yes
1   NaN     No
2   NaN    Yes
3   NaN     No

#### Q2: Convert Yes/No to True/False.

In [56]:
status_map = {"Yes" : "True", "No" : "False"}
df["status"] = df["Status"].map(status_map)
df

  Grade Status status
0   NaN    Yes   True
1   NaN     No  False
2   NaN    Yes   True
3   NaN     No  False

## 🔹 6. replace()

#### Q1: Replace Delhi → NCR.

In [59]:
df = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai"],
    "Grade": ["A", "B", "C", "A"]
})

In [61]:
df["City"].replace({"Delhi" : "Delhi NCR"})

0    Delhi NCR
1       Mumbai
2    Delhi NCR
3      Chennai
Name: City, dtype: object

#### Q2: Replace grades with numbers.

In [63]:
df["Grade"].replace({"A" : 1 , "B" :2 , "C" : 3})

C:\Users\Yash Mishra\AppData\Local\Temp\ipykernel_21108\2249720699.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Grade"].replace({"A" : 1 , "B" :2 , "C" : 3})

0    1
1    2
2    3
3    1
Name: Grade, dtype: int64