In [1]:
import pandas as pd

In [2]:
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'Finance'],
    'Salary': [50000, 60000, 40000, 45000, 70000],
    'Age': [25, 30, 35, 28, 40]
}
df = pd.DataFrame(data)

In [3]:
df.groupby('Department')['Salary'].mean() # Department wise average salary

Department
Finance    70000.0
HR         42500.0
IT         55000.0
Name: Salary, dtype: float64

In [4]:
df.groupby('Department')['Salary'].sum() # every Department Total Salary

Department
Finance     70000
HR          85000
IT         110000
Name: Salary, dtype: int64

In [5]:
df.groupby('Department').agg({        #.groupby() + .agg() use both toh calaculate avaerage salary and max age
    'Salary' : 'mean',
    'Age' : 'max'
})

             Salary  Age
Department
Finance     70000.0   40
HR          42500.0   35
IT          55000.0   30

In [6]:
df["Avg Salary"] = df.groupby('Department')['Salary'].transform('mean') #Add ner coloumn average salary
df

  Department  Salary  Age  Avg Salary
0         IT   50000   25     55000.0
1         IT   60000   30     55000.0
2         HR   40000   35     42500.0
3         HR   45000   28     42500.0
4    Finance   70000   40     70000.0

In [7]:
df[df['Avg Salary']>50000]  # on;y those departments whose average salary has more than 50000.

  Department  Salary  Age  Avg Salary
0         IT   50000   25     55000.0
1         IT   60000   30     55000.0
4    Finance   70000   40     70000.0

## Group by department:
#### total salary
#### average age
#### employee count
#### sab ek hi output me

In [8]:
df.groupby('Department').agg({
    'Salary' : 'sum',
    'Age' : 'mean',
    'Department' : 'count'
})

            Salary   Age  Department
Department
Finance      70000  40.0           1
HR           85000  31.5           2
IT          110000  27.5           2

## Find:
#### Highest salary per department
#### Avg experience per department
#### Departments where avg experience > 4

In [11]:
data2 = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'Finance', 'Finance'],
    'Salary': [50000, 60000, 40000, 45000, 70000, 72000],
    'Experience': [2, 5, 3, 4, 6, 7]
}
df2 = pd.DataFrame(data2)

In [13]:
df2.groupby('Department')['Salary'].max()  #Highest salary per department

Department
Finance    72000
HR         45000
IT         60000
Name: Salary, dtype: int64

In [15]:
df2.groupby('Department')['Experience'].mean()

Department
Finance    6.5
HR         3.5
IT         3.5
Name: Experience, dtype: float64

In [16]:
df2["Avg Experience"] = df.groupby('Department')['Experience'].transform('mean')
df2

  Department  Salary  Experience  Avg Experience
0         IT   50000           2             3.5
1         IT   60000           5             3.5
2         HR   40000           3             3.5
3         HR   45000           4             3.5
4    Finance   70000           6             6.5
5    Finance   72000           7             6.5

In [17]:
df2[df2['Avg Experience'] > 4 ]   #Departments where avg experience > 4

  Department  Salary  Experience  Avg Experience
4    Finance   70000           6             6.5
5    Finance   72000           7             6.5