In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID" : [1,2,3],
    "Name" : ["Yash" ,"Ashish" , "Suraj"],
    "DeptID": [10,20,30]
})

In [4]:
employees

   EmpID    Name  DeptID
0      1    Yash      10
1      2  Ashish      20
2      3   Suraj      30

In [5]:
departments = pd.DataFrame({
    "DeptID" : [10,20,40],
    "DeptName" : ["HR", "Engineering" , "Marketing"]
})

## Merge Like SQL: pd.merge()

In [8]:
pd.merge(employees , departments , on="DeptID") #Inner Join

   EmpID    Name  DeptID     DeptName
0      1    Yash      10           HR
1      2  Ashish      20  Engineering

In [11]:
pd.merge(employees , departments , on="DeptID", how="left") #Left join

   EmpID    Name  DeptID     DeptName
0      1    Yash      10           HR
1      2  Ashish      20  Engineering
2      3   Suraj      30          NaN

In [13]:
pd.merge(employees, departments, on="DeptID", how="right") # Right Join

   EmpID    Name  DeptID     DeptName
0    1.0    Yash      10           HR
1    2.0  Ashish      20  Engineering
2    NaN     NaN      40    Marketing

In [15]:
pd.merge(employees, departments, on="DeptID", how="outer") # Right Join

   EmpID    Name  DeptID     DeptName
0    1.0    Yash      10           HR
1    2.0  Ashish      20  Engineering
2    3.0   Suraj      30          NaN
3    NaN     NaN      40    Marketing

## Concatenating data frames

In [17]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "score": [423, 634]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "age": [45, 78]})

In [18]:
df1

    Name  score
0  Alice    423
1    Bob    634

In [19]:
df2

      Name  age
0  Charlie   45
1    David   78

In [20]:
pd.concat([df1 , df2])

      Name  score   age
0    Alice  423.0   NaN
1      Bob  634.0   NaN
0  Charlie    NaN  45.0
1    David    NaN  78.0

In [22]:
pd.concat([df1 , df2], axis=1)

    Name  score     Name  age
0  Alice    423  Charlie   45
1    Bob    634    David   78