## 🟢 Section 1: Column Selection (df[col])

#### Q1. Select only the age column

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'name': ['Amit', 'Riya', 'John', 'Sara', 'Raj'],
    'age': [20, 17, 22, 19, 18],
    'marks': [85, 90, 45, 70, 30]
})

In [3]:
df['age']

0    20
1    17
2    22
3    19
4    18
Name: age, dtype: int64

#### Q2. Select both name and marks columns

In [4]:
df[['name', 'age']]

   name  age
0  Amit   20
1  Riya   17
2  John   22
3  Sara   19
4   Raj   18

## 🟡 Section 2: .loc[]

#### Q3. Select the row with index 2 using .loc[]

In [5]:
df.loc[1]

name     Riya
age        17
marks      90
Name: 1, dtype: object

#### Q4. Select rows from index 1 to 3 and columns name and marks

In [6]:
df.loc[0:2]

   name  age  marks
0  Amit   20     85
1  Riya   17     90
2  John   22     45

#### Q5. Select the marks column using .loc[] (all rows)

In [7]:
df.loc[: , 'marks']

0    85
1    90
2    45
3    70
4    30
Name: marks, dtype: int64

## 🟠 Section 3: .iloc[]

#### Q6. Select the 3rd row using .iloc[]

In [8]:
df.iloc[2]

name     John
age        22
marks      45
Name: 2, dtype: object

#### Q7. Select the first 4 rows

In [9]:
df.iloc[0:4]

   name  age  marks
0  Amit   20     85
1  Riya   17     90
2  John   22     45
3  Sara   19     70

#### Q8. Select the value at row index 2 and column index 2

In [10]:
df.iloc[2 , 2]

np.int64(45)

## 🔵 Section 4: .at[] and .iat[]

#### Q9. Get the marks value at index 3 using .at[]

In [11]:
df.at[3 , 'marks']

np.int64(70)

#### Q10. Get the same value using .iat[]

In [12]:
df.iat[3 , 2]

np.int64(70)

#### Q11. Get the name at index 0 using .at[]

In [13]:
df.at[0 , 'name']

'Amit'

## 🔴 Section 5: Filtering with Conditions

#### Q12. Filter students with marks greater than 80

In [14]:
df[df['marks'] > 80]

   name  age  marks
0  Amit   20     85
1  Riya   17     90

#### Q13. Filter students where age ≥ 18 AND marks > 50

In [15]:
df[(df['age'] >= 18 ) & (df['marks'] >50)]

   name  age  marks
0  Amit   20     85
3  Sara   19     70

#### Q14. Filter students where marks < 50 OR age < 18

In [16]:
df[(df['marks'] < 50 ) | (df['age'] < 18)]

   name  age  marks
1  Riya   17     90
2  John   22     45
4   Raj   18     30

## 🟣 Section 6: .query()

#### Q15. Filter students with marks > 70 using .query()

In [17]:
df.query("marks > 70")

   name  age  marks
0  Amit   20     85
1  Riya   17     90

#### Q16. Filter students where age > 18 AND marks < 80 using .query()

In [18]:
df.query("age > 18 & marks <80")

   name  age  marks
2  John   22     45
3  Sara   19     70

#### Q17. Using .query(), return only name and marks where marks > 60

In [23]:
df.query("marks > 60") [['name' , 'marks']]

   name  marks
0  Amit     85
1  Riya     90
3  Sara     70

## 🧠 Final Challenge

#### Q18. In a single line:

#### Filter students with marks ≥ 50
#### age < 22
#### Return only the name column
#### (using .query() + selection)

In [25]:
df.query("marks >= 50 & age <22") ['name']

0    Amit
1    Riya
3    Sara
Name: name, dtype: object